apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fts-renew
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: bruzzese/fts-renew
            args: ["bin/bash"]
            command: ["/bin/bash"]
            args: ["-c", "mkdir -p /opt/rucio/etc; cp /tmp/usercert.pem /opt/rucio/etc/usercert.pem; /bin/bash /fts/renew_fts_delegation.sh; cp /tmp/userkey.pem /opt/rucio/etc/userkey.pem; cp /tmp/x509up /opt/rucio/etc/x509up; /opt/user/rucio_init.sh; while true; do echo hello; sleep 3;done"]
            volumeMounts:
            - name: usercert
              mountPath: /etc/grid-security/usercert.pem
              subPath: usercert.pem
            - name: userkey
              mountPath: /etc/grid-security/userkey.pem
              subPath: userkey.pem
          restartPolicy: OnFailure
          volumes:
          - name: usercert
            secret:
              secretName: clients-admin-cert
          - name: userkey
            secret:
              secretName: clients-admin-key
              defaultMode: 0400
