apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fts-renew
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: bruzzese/fts-renew
            command: ["/bin/bash"]
            args: ["/fts/renew_fts_delegation.sh"]
            volumeMounts:
            - name: usercert
              mountPath: /etc/grid-security/usercert.pem
              subPath: usercert.pem
            - name: userkey
              mountPath: /etc/grid-security/userkey.pem
              subPath: userkey.pem
          restartPolicy: OnFailure
          volumes:
          - name: usercert
            secret:
              secretName: clients-admin-cert
          - name: userkey
            secret:
              secretName: clients-admin-key
              defaultMode: 0400
