FROM centos:7
# RUN echo "Building client"

# Required repos
RUN yum install -y wget
ADD "http://dmc-repo.web.cern.ch/dmc-repo/dmc-ci-el7.repo" "/etc/yum.repos.d/"
ADD "http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo" "/etc/yum.repos.d/"
RUN yum -y install https://repo.opensciencegrid.org/osg/3.5/osg-3.5-el7-release-latest.rpm

RUN yum --setopt=tsflags=nodocs -y install epel-release yum-plugin-ovl \
   && yum --setopt=tsflags=nodocs -y install fetch-crl wn sysstat git vim gcc cmake make ca-policy-egi-core ca-policy-lcg \
           voms-clients-cpp voms \
   && yum clean all

RUN yum install -y epel-release.noarch
RUN yum upgrade -y
RUN yum install -y root nano git tree make httpd python3 python3-mod_wsgi libaio gcc python36-devel.x86_64 mod_ssl openssl-devel.x86_64 python3-m2crypto libnsl.x86_64 cronie

# Add voms dependencies 
RUN yum install -y globus-proxy-utils voms-clients-cpp voms-clients-java

# Add gfal dependencies 
RUN yum install -y tree \
   which \
   python3 \
   # fts-clients \
   # fts-rest \
   fts-rest-cli \
   python-setuptools \
   python-requests \
   && yum clean all

RUn yum install -y boost-python36 \
   glib2-devel \
   gtest \
   libattr-devel \
   && yum clean all 

RUN rpm -i /tmp/oic.rpm; \
    echo "/usr/lib/oracle/12.2/client64/lib" >/etc/ld.so.conf.d/oracle.conf; \
    ldconfig

RUN mkdir -p /etc/grid-security

RUN mkdir /fts
WORKDIR /fts
ADD fts/* /fts/

RUN chmod +x /fts/renew_fts_delegation.sh

RUN python3 -m pip install --upgrade pip setuptools

EXPOSE 5000

CMD ["/usr/sbin/init", "/bin/bash", "./entrypoint.sh"]

