apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
  name: regcred
type: kubernetes.io/dockercfg
data:
  dockerRegistry: my-container-registry-url
  dockerId: bruzzese
  dockerPassword: br4912862
