apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: monitoring-admin
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: bruzzese/rucio-admin-monitoring
            command: ["python3"]
            args: ["/rucio-monitoring.py"]
          restartPolicy: OnFailure
          data:
          - RUCIO_CFG_RUCIO_HOST: https://pic01-rucio-server.pic.es:443
          - RUCIO_CFG_AUTH_HOST: https://pic01-rucio-server-auth.pic.es:443
          - RUCIO_CFG_CA_CERT: /etc/grid-security/certificates
          - RUCIO_CFG_AUTH_TYPE: userpass
          - RUCIO_CFG_USERNAME: ddmlab
          - RUCIO_CFG_PASSWORD: secret
          - RUCIO_CFG_ACCOUNT: root
