apiVersion: v1
kind: Pod
metadata:
  name: test-rucio-add-hermes2-v1
  labels:
    app: test-rucio-add-hermes2-v1
spec:
  containers:
  - name: add-hermes2
    image: bruzzese/add-hermes-2:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    args: ["/opt/rucio/etc/hermes2.sh"]
