FROM centos:7
# RUN echo "Building client"

ADD "http://dmc-repo.web.cern.ch/dmc-repo/dmc-ci-el7.repo" "/etc/yum.repos.d/"
ADD "http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo" "/etc/yum.repos.d/"

# Required repos
RUN yum --setopt=tsflags=nodoc install -y epel-release.noarch wget globus-proxy-utils \ 
	voms-clients-cpp voms-clients-java root \
	nano git tree make \ 
	httpd python3 python3-mod_wsgi \ 
	libaio gcc python36-devel.x86_64 \ 
	mod_ssl openssl-devel.x86_64 python3-m2crypto \
	fetch-crl wn sysstat \
	https://repo.opensciencegrid.org/osg/3.5/osg-3.5-el7-release-latest.rpm \
	vim gcc cmake make ca-certificates ca-policy-egi-core \ 
	ca-policy-egi-core ca-policy-lcg yum-plugin-ovl \ 
	libnsl.x86_64 cronie && \
    	yum upgrade -y && \
    	yum clean all && \
    	rm -rf /var/cache/yum/*

# Add gfal dependencies 
RUN rpm -i /tmp/oic.rpm; \
    echo "/usr/lib/oracle/12.2/client64/lib" >/etc/ld.so.conf.d/oracle.conf; \
    ldconfig

RUN mkdir -p /opt/rucio/etc

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --upgrade setuptools \ 
	wheel \
	rucio-clients==1.23.11 \
	numpy \
	pytz

# To generate the configuration and enable bash completion for the rucio clients
ENV PATH $PATH:/opt/rucio/etc
# Add scripts 
ADD ./config/rucio.cfg /opt/rucio/etc/
ADD ./config/bashrc /root/.bashrc
ADD ./config/hermes2.sh /opt/rucio/etc/
RUN chmod 755 /opt/rucio/etc/hermes2.sh

EXPOSE 5000

CMD ["/usr/sbin/init", "/bin/bash", "./entrypoint.sh"]
